<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <AssemblyName>Blink</AssemblyName>
    <Product>Blink</Product>
    <Title>Blink</Title>
    <Company>Blink Team</Company>
    <ApplicationIcon>Blink.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Blink_Payload.zip" Condition="Exists('Blink_Payload.zip')" />
  </ItemGroup>
</Project>
